services:
  loki:
    container_name: ${LZ}_loki_${ENV}
    image: grafana/loki:latest
    ports:
      - 3100:3100
    volumes:
      - ./loki/loki-config.yml:/etc/loki/loki-config.yaml
      - loki_data:/data
    restart: unless-stopped
    networks:
      - local_network
  grafana:
    container_name: ${LZ}_grafana_${ENV}
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    restart: unless-stopped	
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - local_network
  watchtower:
    container_name: ${LZ}_watchtower_${ENV}
    image: containrrr/watchtower:latest
    environment:
      WATCHTOWER_NOTIFICATION_REPORT: "true"
      WATCHTOWER_SCHEDULE: "0 15-23 * * *"  # Run at minute 0 of hours 15-23 (3 PM to 11 PM)
      WATCHTOWER_CLEANUP: true # Remove old images after updates
      TZ: AMERICA/CHICAGO
      WATCHTOWER_NOTIFICATIONS: shoutrrr
      WATCHTOWER_NOTIFICATION_URL: telegram://${BOT_TOKEN}@telegram/?channels=${CHAT_ID}
      WATCHTOWER_NOTIFICATION_TEMPLATE: |
        {{- if .Report -}}
          {{- if .Report.Updated -}}
            Container updates detected:
            {{- range .Report.Updated}}
            - {{.Name}} ({{.ImageName}}): {{.CurrentImageID.ShortID}} → {{.LatestImageID.ShortID}}
            {{- end -}}
          {{- end -}}
        {{- end -}}
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - local_network
volumes:
  grafana_data:
  loki_data:

networks:
  local_network:
    name: "${LZ}_network_${ENV}"
    external: true