services:
  loki:
    image: grafana/loki:latest
    ports:
      - 3100:3100
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yaml
      - loki_data:/data
    restart: unless-stopped	
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    restart: unless-stopped	
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
  loki_data:
