services:
  loki:
    container_name: ${LZ}_loki_${ENV}
    image: grafana/loki:latest
    volumes:
      - ../loki/loki-config.yml:/etc/loki/loki-config.yaml
      - loki_data:/data
    restart: unless-stopped
    networks:
      - gs_network	
  grafana:
    container_name: ${LZ}_grafana_${ENV}
    image: grafana/grafana
    restart: unless-stopped	
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - gs_network
volumes:
  grafana_data:
  loki_data:
networks:
  gs_network: 
    external: true
